version: '3.8'
services:
  load-balance:
    image: nginx:1.16.0-alpine
    ports:
      - "80:80"
    volumes:
      # setup nginx
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/mime.types:/etc/nginx/mime.types:ro

      # website sources
      - ../website:/usr/share/nginx/html

      # setup file or folder public
      - ../assets:/usr/share/nginx/html/assets
      - ./errors:/usr/share/nginx/html/errors
      - ../logs:/etc/nginx/logs
